adds NLP endoscopy project to work
GSTT-CSC/gstt-csc-old pull request #40
Opened 2021-05-24 13:56 UTC by laurencejackson

2021-05-24 14:04 UTC, hshuaib90 requested changes
Can you also please remove the .DS_Store from the commit.

2021-05-24 14:04 UTC, hshuaib90 commented on _data/work.yml
> +  link: projects/AIC016-NLP_endoscopic_resources_optimisation.html
16 is already taken according to https://docs.google.com/spreadsheets/d/1mII4MGBEyfO7FEuJPtCA0AbMIAiuC8sFZLaH64Mpvj4/edit#gid=1453792661. It seems @AnilMistry entry is wrong. @laurencejackson  can you edit his stuffy to AIC016 and change yours to AIC017.

2021-05-25 14:16 UTC, laurencejackson commented on _data/work.yml
> +  link: projects/AIC016-NLP_endoscopic_resources_optimisation.html
Should be fixed now, I've not renamed the branch so we don't need to open another PR, but the content now only refers to this project as AIC017.

2021-05-26 12:19 UTC, hshuaib90 requested changes

2021-05-26 12:19 UTC, hshuaib90 commented on _data/work.yml
> +  link: projects/AIC017-NLP_endoscopic_resources_optimisation.html
Doesn't look like you've merged latest master as ANil's project still has 018

2021-05-26 12:22 UTC, laurencejackson commented on _data/work.yml
> +  link: projects/AIC017-NLP_endoscopic_resources_optimisation.html
should be resolved now

2021-05-26 18:43 UTC, hshuaib90 approved these changes

2021-05-26 18:43 UTC, merged